import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Team, columns } from "./columns";
import { DataTable } from "./data-table";
export default function TeamList() {
  const data: Team[] = [
    {
      id: "Badminton Jr. Co-ed",
      sport: "Badminton",
      gender: "Co-ed",
      grade: "Jr.",
      season: "Winter",
      teachers: ["martin.nicholls@ycdsbk12.ca"],
      points: 10,
    },
    {
      id: "Badminton Sr. Co-ed",
      sport: "Badminton",
      gender: "Co-ed",
      grade: "Sr.",
      season: "Winter",
      teachers: ["richard.ow@ycdsbk12.ca", "tiziana.hayhoe@ycdsbk12.ca"],
      points: 10,
    },
    {
      id: "Baseball Varsity Boys",
      sport: "Baseball",
      gender: "Boys",
      grade: "Varsity",
      season: "Spring",
      teachers: ["michael.morrison@ycdsbk12.ca", "domenico.coccia@ycdsbk12.ca"],
      points: 10,
    },
    {
      id: "Basketball Jr. Boys",
      sport: "Basketball",
      gender: "Boys",
      grade: "Jr.",
      season: "Winter",
      teachers: [
        "jordan.caruso@ycdsbk12.ca",
        "adam.dandrea@ycdsbk12.ca",
        "anthony.petrone@ycdsbk12.ca",
      ],
      points: 10,
    },
    {
      id: "Basketball Sr. Boys",
      sport: "Basketball",
      gender: "Boys",
      grade: "Sr.",
      season: "Fall",
      teachers: [
        "alexander.dasilva@ycdsbk12.ca",
        "michele.petrone@ycdsbk12.ca",
      ],
      points: 10,
    },
    {
      id: "Basketball Jr. Girls",
      sport: "Basketball",
      gender: "Girls",
      grade: "Jr.",
      season: "Fall",
      teachers: ["brian.villavazera@ycdsbk12.ca", "david.beck@ycdsbk12.ca"],
      points: 10,
    },
    {
      id: "Basketball Sr. Girls",
      sport: "Basketball",
      gender: "Girls",
      grade: "Sr.",
      season: "Fall",
      teachers: [
        "alexander.dasilva@ycdsbk12.ca",
        "daniela.bonello@ycdsbk12.ca",
      ],
      points: 10,
    },
    {
      id: "Cross-Country Varsity Co-ed",
      sport: "Cross-Country",
      gender: "Co-ed",
      grade: "Varsity",
      season: "Fall",
      teachers: [
        "jennifer.hickey@ycdsbk12.ca",
        "sabrina.buffa@ycdsbk12.ca",
        "paola.amoroso@ycdsbk12.ca",
      ],
      points: 5,
    },
    {
      id: "Curling Varsity Co-ed",
      sport: "Curling",
      gender: "Co-ed",
      grade: "Varsity",
      season: "Winter",
      teachers: [
        "alexandra.carvier@ycdsbk12.ca",
        "michael.onorati@ycdsbk12.ca",
      ],
      points: 10,
    },
    {
      id: "Golf Varsity Co-ed",
      sport: "Golf",
      gender: "Co-ed",
      grade: "Varsity",
      season: "Fall",
      teachers: ["tiziana.hayhoe@ycdsbk12.ca", "martin.nicholls@ycdsbk12.ca"],
      points: 10,
    },
    {
      id: "Hockey Varsity Boys",
      sport: "Hockey",
      gender: "Boys",
      grade: "Varsity",
      season: "Winter",
      teachers: [
        "dan.nero@ycdsbk12.ca",
        "mark.johnson@ycdsbk12.ca",
        "michael.morrison@ycdsbk12.ca",
      ],
      points: 10,
    },
    {
      id: "Hockey Varsity Girls",
      sport: "Hockey",
      gender: "Girls",
      grade: "Varsity",
      season: "Winter",
      teachers: [
        "michael.stevan@ycdsbk12.ca",
        "michael.merlocco@ycdsbk12.ca",
        "rocky.savoia@ycdsbk12.ca",
      ],
      points: 10,
    },
    {
      id: "Rock Climbing Varsity Co-ed",
      sport: "Rock Climbing",
      gender: "Co-ed",
      grade: "Varsity",
      season: "Winter",
      teachers: ["michael.onorati@ycdsbk12.ca", "george.azar@ycdsbk12.ca"],
      points: 5,
    },
    {
      id: "Rugby Jr. Boys",
      sport: "Rugby",
      gender: "Boys",
      grade: "Jr.",
      season: "Spring",
      teachers: [
        "george.azar@ycdsbk12.ca",
        "michael.onorati@ycdsbk12.ca",
        "mark.johnson@ycdsbk12.ca",
        "rocky.savoia@ycdsbk12.ca",
      ],
      points: 10,
    },
    {
      id: "Rugby Sr. Boys",
      sport: "Rugby",
      gender: "Boys",
      grade: "Sr.",
      season: "Spring",
      teachers: [
        "george.azar@ycdsbk12.ca",
        "michael.onorati@ycdsbk12.ca",
        "mark.johnson@ycdsbk12.ca",
        "rocky.savoia@ycdsbk12.ca",
      ],
      points: 10,
    },
    {
      id: "Rugby Sevens Jr. Boys",
      sport: "Rugby Sevens",
      gender: "Boys",
      grade: "Jr.",
      season: "Fall",
      teachers: [
        "michael.onorati@ycdsbk12.ca",
        "george.azar@ycdsbk12.ca",
        "rocky.savoia@ycdsbk12.ca",
        "mark.johnson@ycdsbk12.ca",
      ],
      points: 10,
    },
    {
      id: "Rugby Sevens Sr. Boys",
      sport: "Rugby Sevens",
      gender: "Boys",
      grade: "Sr.",
      season: "Fall",
      teachers: [
        "george.azar@ycdsbk12.ca",
        "michael.onorati@ycdsbk12.ca",
        "mark.johnson@ycdsbk12.ca",
        "rocky.savoia@ycdsbk12.ca",
      ],
      points: 10,
    },
    {
      id: "Rugby Sevens Varsity Girls",
      sport: "Rugby Sevens",
      gender: "Girls",
      grade: "Varsity",
      season: "Fall",
      teachers: ["stephanie.veitch@ycdsbk12.ca", "michael.onorati@ycdsbk12.ca"],
      points: 10,
    },
    {
      id: "Slow Pitch Varsity Co-ed",
      sport: "Slow Pitch",
      gender: "Co-ed",
      grade: "Varsity",
      season: "Spring",
      teachers: [
        "tiziana.hayhoe@ycdsbk12.ca",
        "melina.tedesco@ycdsbk12.ca",
        "natalie.ligato@ycdsbk12.ca",
      ],
      points: 10,
    },
    {
      id: "Soccer Jr. Boys",
      sport: "Soccer",
      gender: "Boys",
      grade: "Jr.",
      season: "Fall",
      teachers: ["michele.petrone@ycdsbk12.ca", "domenico.coccia@ycdsbk12.ca"],
      points: 10,
    },
    {
      id: "Soccer Sr. Boys",
      sport: "Soccer",
      gender: "Boys",
      grade: "Sr.",
      season: "Fall",
      teachers: [
        "steven.sedran@ycdsbk12.ca",
        "michal.kirejczyk@ycdsbk12.ca",
        "anthony.petrone@ycdsbk12.ca",
      ],
      points: 10,
    },
    {
      id: "Soccer Jr. Girls",
      sport: "Soccer",
      gender: "Girls",
      grade: "Jr.",
      season: "Spring",
      teachers: ["jordan.caruso@ycdsbk12.ca", "anthony.petrone@ycdsbk12.ca"],
      points: 10,
    },
    {
      id: "Soccer Sr. Girls",
      sport: "Soccer",
      gender: "Girls",
      grade: "Sr.",
      season: "Spring",
      teachers: [
        "alessia.landolfi@ycdsbk12.ca",
        "michal.kirejczyk@ycdsbk12.ca",
        "steven.sedran@ycdsbk12.ca",
        "michele.petrone@ycdsbk12.ca",
      ],
      points: 10,
    },
    {
      id: "Swimming Varsity Co-ed",
      sport: "Swimming",
      gender: "Co-ed",
      grade: "Varsity",
      season: "Winter",
      teachers: [
        "manuel.decompa@ycdsbk12.ca",
        "antonette.montanaro@ycdsbk12.ca",
        "alaa.al-shaikh@ycdsbk12.ca",
        "vanessa.vitale@ycdsbk12.ca",
      ],
      points: 10,
    },
    {
      id: "Table Tennis Varsity Co-ed",
      sport: "Table Tennis",
      gender: "Co-ed",
      grade: "Varsity",
      season: "Fall",
      teachers: ["david.beck@ycdsbk12.ca"],
      points: 10,
    },
    {
      id: "Tennis Varsity Co-ed",
      sport: "Tennis",
      gender: "Co-ed",
      grade: "Varsity",
      season: "Fall",
      teachers: ["raimondo.pupolo@ycdsbk12.ca", "victoria.ah-chin@ycdsbk12.ca"],
      points: 10,
    },
    {
      id: "Track(Outdoor) Varsity Co-ed",
      sport: "Track(Outdoor)",
      gender: "Co-ed",
      grade: "Varsity",
      season: "Spring",
      teachers: [
        "roberto.rizzo@ycdsbk12.ca",
        "daniela.bonello@ycdsbk12.ca",
        "sabrina.buffa@ycdsbk12.ca",
        "julia.loschiavo@ycdsbk12.ca",
        "lori.gentile@ycdsbk12.ca",
      ],
      points: 10,
    },
    {
      id: "Ultimate Frisbee Varsity Co-ed",
      sport: "Ultimate Frisbee",
      gender: "Co-ed",
      grade: "Varsity",
      season: "Spring",
      teachers: ["david.west@ycdsbk12.ca"],
      points: 10,
    },
    {
      id: "Volleyball Jr. Boys",
      sport: "Volleyball",
      gender: "Boys",
      grade: "Jr.",
      season: "Fall",
      teachers: ["adam.dandrea@ycdsbk12.ca"],
      points: 10,
    },
    {
      id: "Volleyball Sr. Boys",
      sport: "Volleyball",
      gender: "Boys",
      grade: "Sr.",
      season: "Fall",
      teachers: ["michael.morrison@ycdsbk12.ca", "david.west@ycdsbk12.ca"],
      points: 10,
    },
    {
      id: "Volleyball Jr. Girls",
      sport: "Volleyball",
      gender: "Girls",
      grade: "Jr.",
      season: "Fall",
      teachers: ["david.beck@ycdsbk12.ca"],
      points: 10,
    },
    {
      id: "Volleyball Sr. Girls",
      sport: "Volleyball",
      gender: "Girls",
      grade: "Sr.",
      season: "Winter",
      teachers: [
        "stephanie.veitch@ycdsbk12.ca",
        "kasia.bak@ycdsbk12.ca",
        "lucy.araujo@ycdsbk12.ca",
      ],
      points: 10,
    },
  ];

  return (
    <div className="px-16 py-24">
      <div className="text-3xl font-bold mb-2">Team List</div>
      <div className="flex gap-4 items-center mb-8">
        <span>Select a season:</span>
        <Select>
          <SelectTrigger className="w-auto">
            <SelectValue placeholder="Select" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="light">2025-26</SelectItem>
            <SelectItem value="dark">2024-25</SelectItem>
            <SelectItem value="system">2023-24</SelectItem>
          </SelectContent>
        </Select>
      </div>
      <DataTable columns={columns} data={data} />
    </div>
  );
}
